spring:
  config:
    activate:
      on-profile: prod
  application:
    name: donercloud
  datasource:
    generate-unique-name: false
    name: donercloud
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
  cassandra:
    keyspace-name: donercloud
    schema-action: recreate
    local-datacenter: datacenter1

server:
  port: 8443
  ssl:
    key-store: file:mykeys.jks
    key-store-password: letmein
    key-password: letmein

logging:
  file:
    path: ./logs/
    file: TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: warn
        ##jdbc.datasource.init.ScriptUtils: WARN

taco:
  orders:
   page-size: 5
