spring:
  application:
    name: donercloud
  datasource:
    generate-unique-name: false
    name: donercloud
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /api
  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  h2:
    console:
      enabled: true

server:
  port: 8333
##  ssl:
  ##  key-store: file:mykeys.jks
    ##key-store-password: letmein
    ##key-password: letmein

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    org:
      springframework:
        security: warn
        jdbc.datasource.init.ScriptUtils: WARN
        data.rest.webmvc: DEBUG

taco:
  orders:
   page-size: 5
